version: "3.9"

services:
  zookeeper:
    image: zookeeper
    expose:
      - 2181

  kafka-server:
    image: bitnami/kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  aerospike:
    image: aerospike/aerospike-server:6.3.0.4
    environment:
      NAMESPACE: tinychat
      DEFAULT_TTL: 1D
      NSUP_PERIOD: 60
      MEM_GB: 1
    ports:
      - "3000-3002:3000-3002"